.TH "S:/PROGRAMMING/CPP/ecs/include/ComponentWrapper.h" 3 "Sat Aug 28 2021" "Version 0.1.0" "Entity Component System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/PROGRAMMING/CPP/ecs/include/ComponentWrapper.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Util\&.h'\fP
.br
\fC#include '\&.\&./src/ComponentWrapper\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBecs::ComponentWrapper< ComponentT >\fP"
.br
.RI "Class wrapping components for \fBComponentBuffer\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBecs\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Entity Component System from the source code\&.
