.TH "S:/PROGRAMMING/CPP/ecs/include/ComponentBuffer.h" 3 "Sat Aug 28 2021" "Version 0.1.0" "Entity Component System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/PROGRAMMING/CPP/ecs/include/ComponentBuffer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Meta\&.h'\fP
.br
\fC#include 'ComponentWrapper\&.h'\fP
.br
\fC#include '\&.\&./src/ComponentBuffer\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBecs::ComponentBuffer< meta::TypeList< Typepack\&.\&.\&. > >\fP"
.br
.RI "The \fBComponentBuffer\fP handling entities' conmponents\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBecs\fP"
.br
.ti -1c
.RI " \fBecs::meta\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Typepack> using \fBecs::meta::ComponentPool\fP = TypeList< Typepack \&.\&.\&. >"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Entity Component System from the source code\&.
