.TH "ecs" 3 "Sat Aug 28 2021" "Version 0.1.0" "Entity Component System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBimpl\fP"
.br
.ti -1c
.RI " \fBmeta\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBComponentBuffer\fP"
.br
.RI "Class predeclaration\&. "
.ti -1c
.RI "class \fBComponentBuffer< meta::TypeList< Typepack\&.\&.\&. > >\fP"
.br
.RI "The \fBComponentBuffer\fP handling entities' conmponents\&. "
.ti -1c
.RI "class \fBComponentWrapper\fP"
.br
.RI "Class wrapping components for \fBComponentBuffer\fP\&. "
.ti -1c
.RI "class \fBInterface\fP"
.br
.RI "Class representing interface used in ECS systems\&. "
.ti -1c
.RI "class \fBManager\fP"
.br
.ti -1c
.RI "class \fBThreadPool\fP"
.br
.RI "The class representing dynamic pool of computing threads\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Entity Component System from the source code\&.
