.TH "ecs::meta" 3 "Sat Aug 28 2021" "Version 0.1.0" "Entity Component System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecs::meta
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Typepack> using \fBComponentPool\fP = TypeList< Typepack \&.\&.\&. >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "template<typename\&.\&.\&. Typepack> using \fBecs::meta::ComponentPool\fP = typedef TypeList<Typepack \&.\&.\&.>"

.SH "Author"
.PP 
Generated automatically by Doxygen for Entity Component System from the source code\&.
